# Generated by Django 5.1.1 on 2025-05-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name', 'price'], name='core_servic_name_ac9bea_idx'),
        ),
    ]
